### PR TITLE
another update for Julia 0.5

### PR DESCRIPTION
**Pull request by CarloLucibello**
@andrewcooke could you tag a new version after merging this?

### CODE REVIEW

**Comment by CarloLucibello** [comment]
bumpity bump for merging this and tagging a new version (LightGraphs won't work on 0.5 otherwise)

**Comment by andrewcooke** [comment]
plan to look at this next week when i have some time off work.

**Comment by andrewcooke** [comment]
will tag soon - just looking at tests, etc

**Comment by andrewcooke** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/5984

thanks!

**Pull request merged**
