### PR TITLE
Fix broken badge URL

### PR DESCRIPTION
**Pull request by IainNZ**

### CODE REVIEW

**Comment by andrewcooke** [comment]
oh, thnaks.  i was planning to look at that some time soon, but have a weird bug in the parser that's sucking time.

**Comment by IainNZ** [comment]
I think it was because you were using HTTPS. There is a button on the website to get the Markdown code.

**Comment by andrewcooke** [comment]
yeah https is broken because the cert doesn't match the url.

**Comment by IainNZ** [comment]
More precisely, Github Pages doesn't support SSL for custom domain names

**Pull request merged**
