### PR TITLE
Switch to Project.toml and remove Nullable dependency

### PR DESCRIPTION
**Pull request by alyst**
This package is required by *GraphIO.jl*, so I'm refreshing it to work on current Julia versions (1.x):
  * replace `Nullable{T}` with `Union{T, Nothing}` and drop *Nullable.jl* dependency
  * replace *REQUIRE* with *Project.toml* (using *gen_project.jl*) script

It also makes sense to set up @JuliaRegistrator and @JuliaTagBot for the repository.

### CODE REVIEW

**Comment by alyst** [comment]
Bump :)
I might do a few other touches to this PR (in particular, to improve the coverage), but it would be nice to know whether the merging would be possible in principle.

**Comment by CarloLucibello** [comment]
Hi, I can merge your PR but probably I don't have permissions to activate registrator/tagbot and @andrewcooke is awol. We could merge this when you are ready and then fork if needed

**Comment by alyst** [comment]
I think it's ready for review. The coverage fell, but the tests didn't change. So it looks that's because the identification of coverable lines has changed.

**Comment by alyst** [comment]
I've rebased the branch against the current master, updated GitHub actions and switched to GitHub CI. Would be nice to merge :)

**Pull request merged**
